CREATE TABLE [dbo].[Invoice] (
    [InvoiceId]  BIGINT           IDENTITY (1, 1) NOT NULL,
    [OwnerId]    UNIQUEIDENTIFIER NOT NULL,
    [PartnerId]  UNIQUEIDENTIFIER NOT NULL,
    [PurchaseId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED ([InvoiceId] ASC)
);

