//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resourses.RH", typeof(RH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contract.
        /// </summary>
        internal static string add_contract {
            get {
                return ResourceManager.GetString("add_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contract Information.
        /// </summary>
        internal static string add_contract_info {
            get {
                return ResourceManager.GetString("add_contract_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Edit Goods.
        /// </summary>
        internal static string add_edit_goods {
            get {
                return ResourceManager.GetString("add_edit_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Acc. Person.
        /// </summary>
        internal static string add_mol {
            get {
                return ResourceManager.GetString("add_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Accountable person.
        /// </summary>
        internal static string add_mol_info {
            get {
                return ResourceManager.GetString("add_mol_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new parthner.
        /// </summary>
        internal static string add_new_parthner {
            get {
                return ResourceManager.GetString("add_new_parthner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string add_new_user {
            get {
                return ResourceManager.GetString("add_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new parthner.
        /// </summary>
        internal static string add_parthners {
            get {
                return ResourceManager.GetString("add_parthners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address_grid {
            get {
                return ResourceManager.GetString("address_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string administration {
            get {
                return ResourceManager.GetString("administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Role.
        /// </summary>
        internal static string administration_role {
            get {
                return ResourceManager.GetString("administration_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All available Acc persons..
        /// </summary>
        internal static string all_available_MOLS {
            get {
                return ResourceManager.GetString("all_available_MOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        internal static string assigned_to {
            get {
                return ResourceManager.GetString("assigned_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach/Detach.
        /// </summary>
        internal static string att_detach {
            get {
                return ResourceManager.GetString("att_detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank:.
        /// </summary>
        internal static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Transfer.
        /// </summary>
        internal static string bank_transfer {
            get {
                return ResourceManager.GetString("bank_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btn_save_new_price_wharehouse {
            get {
                return ResourceManager.GetString("btn_save_new_price_wharehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulstat.
        /// </summary>
        internal static string bulstat_grid {
            get {
                return ResourceManager.GetString("bulstat_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulstat:.
        /// </summary>
        internal static string bulstat_number {
            get {
                return ResourceManager.GetString("bulstat_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash:.
        /// </summary>
        internal static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change:.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Acc. Person.
        /// </summary>
        internal static string choose_company_mol {
            get {
                return ResourceManager.GetString("choose_company_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Information.
        /// </summary>
        internal static string client_info {
            get {
                return ResourceManager.GetString("client_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аddress:.
        /// </summary>
        internal static string company_address_orders {
            get {
                return ResourceManager.GetString("company_address_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulstat Number:.
        /// </summary>
        internal static string company_bulstat {
            get {
                return ResourceManager.GetString("company_bulstat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string company_email_orders {
            get {
                return ResourceManager.GetString("company_email_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Info.
        /// </summary>
        internal static string company_info {
            get {
                return ResourceManager.GetString("company_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name:.
        /// </summary>
        internal static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner&apos;s name:.
        /// </summary>
        internal static string company_name_orders {
            get {
                return ResourceManager.GetString("company_name_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone:.
        /// </summary>
        internal static string company_phone_orders {
            get {
                return ResourceManager.GetString("company_phone_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number:.
        /// </summary>
        internal static string company_vat_number {
            get {
                return ResourceManager.GetString("company_vat_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string companyname_grid {
            get {
                return ResourceManager.GetString("companyname_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connected to:.
        /// </summary>
        internal static string connected_to_server {
            get {
                return ResourceManager.GetString("connected_to_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        internal static string contracts {
            get {
                return ResourceManager.GetString("contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new User.
        /// </summary>
        internal static string create_new_user {
            get {
                return ResourceManager.GetString("create_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string created_at {
            get {
                return ResourceManager.GetString("created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current price.
        /// </summary>
        internal static string current_price_list_warehouse {
            get {
                return ResourceManager.GetString("current_price_list_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat:.
        /// </summary>
        internal static string DDS {
            get {
                return ResourceManager.GetString("DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Acc. Person.
        /// </summary>
        internal static string delete_mol {
            get {
                return ResourceManager.GetString("delete_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string delete_user {
            get {
                return ResourceManager.GetString("delete_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description_grid_goods {
            get {
                return ResourceManager.GetString("description_grid_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Settings.
        /// </summary>
        internal static string directory_settings {
            get {
                return ResourceManager.GetString("directory_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing company Info failed!.
        /// </summary>
        internal static string edit_company_fail_error {
            get {
                return ResourceManager.GetString("edit_company_fail_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Info.
        /// </summary>
        internal static string edit_company_info {
            get {
                return ResourceManager.GetString("edit_company_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Contract.
        /// </summary>
        internal static string edit_contract {
            get {
                return ResourceManager.GetString("edit_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        internal static string edit_goods {
            get {
                return ResourceManager.GetString("edit_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Acc. Person.
        /// </summary>
        internal static string edit_mol {
            get {
                return ResourceManager.GetString("edit_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Pricelist.
        /// </summary>
        internal static string edit_pricelist {
            get {
                return ResourceManager.GetString("edit_pricelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string edit_user {
            get {
                return ResourceManager.GetString("edit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user information.
        /// </summary>
        internal static string edit_user_info {
            get {
                return ResourceManager.GetString("edit_user_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email_grid {
            get {
                return ResourceManager.GetString("email_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some required fields are empty!.
        /// </summary>
        internal static string empty_username_or_password {
            get {
                return ResourceManager.GetString("empty_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please filll fileds Name and Type of Goods.
        /// </summary>
        internal static string enter_text_error {
            get {
                return ResourceManager.GetString("enter_text_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting Accauntable person!.
        /// </summary>
        internal static string error_deleting_mol {
            get {
                return ResourceManager.GetString("error_deleting_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting selecting user!.
        /// </summary>
        internal static string error_deleting_user {
            get {
                return ResourceManager.GetString("error_deleting_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        internal static string export_to_csv {
            get {
                return ResourceManager.GetString("export_to_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving failed! Please try again!.
        /// </summary>
        internal static string fail_error_settings {
            get {
                return ResourceManager.GetString("fail_error_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string firstname_grid {
            get {
                return ResourceManager.GetString("firstname_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date:.
        /// </summary>
        internal static string from_date {
            get {
                return ResourceManager.GetString("from_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice.
        /// </summary>
        internal static string generate_invoice {
            get {
                return ResourceManager.GetString("generate_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        internal static string goods_tab {
            get {
                return ResourceManager.GetString("goods_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN:.
        /// </summary>
        internal static string iban {
            get {
                return ResourceManager.GetString("iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters! Please fill all fields!.
        /// </summary>
        internal static string invalid_data {
            get {
                return ResourceManager.GetString("invalid_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User!.
        /// </summary>
        internal static string invalid_user {
            get {
                return ResourceManager.GetString("invalid_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        internal static string invalid_username_or_password {
            get {
                return ResourceManager.GetString("invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string invoice_date {
            get {
                return ResourceManager.GetString("invoice_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax event Date.
        /// </summary>
        internal static string invoice_date_DDS {
            get {
                return ResourceManager.GetString("invoice_date_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number.
        /// </summary>
        internal static string invoice_number {
            get {
                return ResourceManager.GetString("invoice_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number:.
        /// </summary>
        internal static string invoice_order {
            get {
                return ResourceManager.GetString("invoice_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string item_description_wharehouse {
            get {
                return ResourceManager.GetString("item_description_wharehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods infromation.
        /// </summary>
        internal static string item_info_order {
            get {
                return ResourceManager.GetString("item_info_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        internal static string item_name {
            get {
                return ResourceManager.GetString("item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        internal static string item_name_wharehouse {
            get {
                return ResourceManager.GetString("item_name_wharehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item type.
        /// </summary>
        internal static string item_type {
            get {
                return ResourceManager.GetString("item_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Good.
        /// </summary>
        internal static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Good.
        /// </summary>
        internal static string label_name_goods {
            get {
                return ResourceManager.GetString("label_name_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:  goods found.
        /// </summary>
        internal static string label_total_goods {
            get {
                return ResourceManager.GetString("label_total_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Good.
        /// </summary>
        internal static string label_type_goods {
            get {
                return ResourceManager.GetString("label_type_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lastname_grid {
            get {
                return ResourceManager.GetString("lastname_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of purchased items:.
        /// </summary>
        internal static string list_with_items {
            get {
                return ResourceManager.GetString("list_with_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged on as:.
        /// </summary>
        internal static string logged_as_current_user {
            get {
                return ResourceManager.GetString("logged_as_current_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (logout).
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main navigation.
        /// </summary>
        internal static string main_navigation {
            get {
                return ResourceManager.GetString("main_navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make primery.
        /// </summary>
        internal static string make_primery {
            get {
                return ResourceManager.GetString("make_primery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage company.
        /// </summary>
        internal static string manage_company {
            get {
                return ResourceManager.GetString("manage_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Accountable persons.
        /// </summary>
        internal static string manage_mol {
            get {
                return ResourceManager.GetString("manage_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        internal static string manage_users {
            get {
                return ResourceManager.GetString("manage_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string measurment_unit {
            get {
                return ResourceManager.GetString("measurment_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc. person.
        /// </summary>
        internal static string mol {
            get {
                return ResourceManager.GetString("mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Goods.
        /// </summary>
        internal static string name_goods {
            get {
                return ResourceManager.GetString("name_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        internal static string name_goods_pricelist {
            get {
                return ResourceManager.GetString("name_goods_pricelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found!.
        /// </summary>
        internal static string no_results_found {
            get {
                return ResourceManager.GetString("no_results_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLD PRICE:.
        /// </summary>
        internal static string old_price_wharehouse {
            get {
                return ResourceManager.GetString("old_price_wharehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance can run at the same time!.
        /// </summary>
        internal static string only_one_instance_at_a_time {
            get {
                return ResourceManager.GetString("only_one_instance_at_a_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner ID.
        /// </summary>
        internal static string partner_Id_grid {
            get {
                return ResourceManager.GetString("partner_Id_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password?.
        /// </summary>
        internal static string password_change {
            get {
                return ResourceManager.GetString("password_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords does not match!.
        /// </summary>
        internal static string password_mismatch {
            get {
                return ResourceManager.GetString("password_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount:.
        /// </summary>
        internal static string payment_amount {
            get {
                return ResourceManager.GetString("payment_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type:.
        /// </summary>
        internal static string payment_type {
            get {
                return ResourceManager.GetString("payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save invoices to:.
        /// </summary>
        internal static string pdf_save_location {
            get {
                return ResourceManager.GetString("pdf_save_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone_grid {
            get {
                return ResourceManager.GetString("phone_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price each.
        /// </summary>
        internal static string price_each {
            get {
                return ResourceManager.GetString("price_each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter price.
        /// </summary>
        internal static string price_list_form_error {
            get {
                return ResourceManager.GetString("price_list_form_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per each good.
        /// </summary>
        internal static string price_per_each_grid_good {
            get {
                return ResourceManager.GetString("price_per_each_grid_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primery Accountable person. You can have only one.
        /// </summary>
        internal static string primery_MOL {
            get {
                return ResourceManager.GetString("primery_MOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        internal static string product_info {
            get {
                return ResourceManager.GetString("product_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information for orders.
        /// </summary>
        internal static string purchase_data_order {
            get {
                return ResourceManager.GetString("purchase_data_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Info.
        /// </summary>
        internal static string purchase_info {
            get {
                return ResourceManager.GetString("purchase_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of purchase:.
        /// </summary>
        internal static string purchased_date {
            get {
                return ResourceManager.GetString("purchased_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of purchase:.
        /// </summary>
        internal static string purchased_date_order {
            get {
                return ResourceManager.GetString("purchased_date_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity_grid_goods {
            get {
                return ResourceManager.GetString("quantity_grid_goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рecipient.
        /// </summary>
        internal static string recipient {
            get {
                return ResourceManager.GetString("recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Acc. Person:.
        /// </summary>
        internal static string recipient_mol {
            get {
                return ResourceManager.GetString("recipient_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove primery.
        /// </summary>
        internal static string remove_primery {
            get {
                return ResourceManager.GetString("remove_primery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string repeat_password {
            get {
                return ResourceManager.GetString("repeat_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string report_for {
            get {
                return ResourceManager.GetString("report_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods movement report.
        /// </summary>
        internal static string report_for_goods_movement {
            get {
                return ResourceManager.GetString("report_for_goods_movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram by:.
        /// </summary>
        internal static string report_unit {
            get {
                return ResourceManager.GetString("report_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted access?.
        /// </summary>
        internal static string restricted_user {
            get {
                return ResourceManager.GetString("restricted_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram for bought/sold items.
        /// </summary>
        internal static string sales_diagram {
            get {
                return ResourceManager.GetString("sales_diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for bought/ sold items.
        /// </summary>
        internal static string sales_report {
            get {
                return ResourceManager.GetString("sales_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by client name.
        /// </summary>
        internal static string search_by_contract_name {
            get {
                return ResourceManager.GetString("search_by_contract_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name or VAT Number.
        /// </summary>
        internal static string search_company_name {
            get {
                return ResourceManager.GetString("search_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name or item code:.
        /// </summary>
        internal static string search_info {
            get {
                return ResourceManager.GetString("search_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by company name.
        /// </summary>
        internal static string search_info_order {
            get {
                return ResourceManager.GetString("search_info_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by numer or name of good.
        /// </summary>
        internal static string search_item_order {
            get {
                return ResourceManager.GetString("search_item_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Transactions.
        /// </summary>
        internal static string search_transactions {
            get {
                return ResourceManager.GetString("search_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        internal static string settings_tab {
            get {
                return ResourceManager.GetString("settings_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Item.
        /// </summary>
        internal static string specific_item {
            get {
                return ResourceManager.GetString("specific_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved cussessfully!.
        /// </summary>
        internal static string success_error_settings {
            get {
                return ResourceManager.GetString("success_error_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Acc. Person:.
        /// </summary>
        internal static string supplier_mol {
            get {
                return ResourceManager.GetString("supplier_mol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string supplyer {
            get {
                return ResourceManager.GetString("supplyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagrams.
        /// </summary>
        internal static string tab_diagrams {
            get {
                return ResourceManager.GetString("tab_diagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct sales.
        /// </summary>
        internal static string tab_page_direct_sales {
            get {
                return ResourceManager.GetString("tab_page_direct_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string tab_reports {
            get {
                return ResourceManager.GetString("tab_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tansactions.
        /// </summary>
        internal static string tansactions {
            get {
                return ResourceManager.GetString("tansactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price list.
        /// </summary>
        internal static string tb_price_list_wharehouse {
            get {
                return ResourceManager.GetString("tb_price_list_wharehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development.
        /// </summary>
        internal static string tb_under_development_wharehouse {
            get {
                return ResourceManager.GetString("tb_under_development_wharehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Invoice for this sale!.
        /// </summary>
        internal static string there_is_no_invoice {
            get {
                return ResourceManager.GetString("there_is_no_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date:.
        /// </summary>
        internal static string to_date {
            get {
                return ResourceManager.GetString("to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount:.
        /// </summary>
        internal static string total_amount {
            get {
                return ResourceManager.GetString("total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Transactions:.
        /// </summary>
        internal static string total_transactions {
            get {
                return ResourceManager.GetString("total_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string tp_orders {
            get {
                return ResourceManager.GetString("tp_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type_goods_pricelist {
            get {
                return ResourceManager.GetString("type_goods_pricelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error - please try again!.
        /// </summary>
        internal static string unknow_error {
            get {
                return ResourceManager.GetString("unknow_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such user already exists!.
        /// </summary>
        internal static string user_already_exist {
            get {
                return ResourceManager.GetString("user_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role.
        /// </summary>
        internal static string user_role {
            get {
                return ResourceManager.GetString("user_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A User with the same username already exist! Please select a new one!.
        /// </summary>
        internal static string username_already_exist {
            get {
                return ResourceManager.GetString("username_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Multiplier in percent ( for example: 0.2).
        /// </summary>
        internal static string vat_multiplier {
            get {
                return ResourceManager.GetString("vat_multiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number:.
        /// </summary>
        internal static string vat_number {
            get {
                return ResourceManager.GetString("vat_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Settings.
        /// </summary>
        internal static string vat_settings {
            get {
                return ResourceManager.GetString("vat_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        internal static string vatnumber_grid {
            get {
                return ResourceManager.GetString("vatnumber_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Invoice.
        /// </summary>
        internal static string view_invoice {
            get {
                return ResourceManager.GetString("view_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Transaction Details.
        /// </summary>
        internal static string view_transaction_details {
            get {
                return ResourceManager.GetString("view_transaction_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Transactions.
        /// </summary>
        internal static string view_transactions {
            get {
                return ResourceManager.GetString("view_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recepit number:.
        /// </summary>
        internal static string warehouse_recepit_order {
            get {
                return ResourceManager.GetString("warehouse_recepit_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werehouse.
        /// </summary>
        internal static string werehouse {
            get {
                return ResourceManager.GetString("werehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale?.
        /// </summary>
        internal static string wholesale {
            get {
                return ResourceManager.GetString("wholesale", resourceCulture);
            }
        }
    }
}
