//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB3Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedItem
    {
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public System.Guid PurchaseId { get; set; }
        public System.Guid ItemId { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Item Item { get; set; }
    }
}
