//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB3Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.PurchasedItems = new HashSet<PurchasedItem>();
        }
    
        public System.Guid PurchaseId { get; set; }
        public System.Guid BuyerId { get; set; }
        public System.Guid SellerId { get; set; }
        public System.DateTime Date { get; set; }
        public string InvoiceId { get; set; }
        public string WareHouseReceipt { get; set; }
    
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasedItem> PurchasedItems { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
