//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB3Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesmapping
    {
        public int Sale_id { get; set; }
        public int Goods_id { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
