//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB3Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SoldItems = new HashSet<SoldItem>();
        }
    
        public System.Guid SaleId { get; set; }
        public System.Guid BuyerId { get; set; }
        public System.Guid SellerId { get; set; }
        public System.DateTime Date { get; set; }
        public int Type { get; set; }
        public Nullable<long> InvoiceId { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoldItem> SoldItems { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
